apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: foldingathome
    helm.sh/chart: foldingathome
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.xml:
    <config>
      {{ range $key, $value := .Values.foldingathome.config }}
      <{{ $key }} v='{{ $value }}'/>
      {{ end }}
      {{ range $key, $value := .Values.foldingathome.slots }}
      <slot id='{{ $key }}' type='{{ $value }}'/>
      {{ end }}
    </config>
