{{- range .Values.priority }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .name }}
value: {{ .value }}
globalDefault: {{ .default | default false }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.foldingathome.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
{{- if .Values.foldingathome.priorityClassName }}
      priorityClassName: {{ .Values.foldingathome.priorityClassName }}
{{- end }}
      containers:
      - name: foldingathome
        image: {{ .Values.foldingathome.image }}
{{- if .Values.foldingathome.env }}
        env:
        {{- range $name, $value := .Values.foldingathome.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
{{- end }}
        # FAHClient renames the given config to update with the slots, we need
        # to have an actual file not the configmap being passed to it.
          command: ["/bin/bash", "-c", "echo 'RUNNING FAHCLIENT'; mkdir -p /etc/fahclient; cp /config.xml /etc/fahclient/config.xml && /app/usr/bin/FAHClient --config /etc/fahclient/config.xml"]
        volumeMounts:
        - name: foldingathome
          mountPath: /config.xml
          subPath: config.xml
        resources:
{{ toYaml .Values.foldingathome.resources | indent 10 }}
      nodeSelector:
{{ toYaml .Values.foldingathome.nodeSelector | indent 8 }}
      volumes:
      - name: foldingathome
        configMap:
          name: cm-{{ .Release.Name }}
---
{{- if .Values.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-{{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPU }}
{{- if .Values.hpa.targetMemory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetMemory }}
{{- end }}
{{- end }}
